#ArtMap Config

#Use "/artmap reload" or restart your server to reload your configurations

#Currently supported languages: [english, mandarin, dutch, russian, german, italian, custom]
#Set language to "custom" and reload to generate a customizable lang.yml in your /plugins/ArtMap folder
language: english

#The name of the world where your players are using ArtMap
world: world

#The number of seconds between each time in-progress artworks are auto-saved to memory
artworkAutoSave: 300

#If true, prevents players from using obvious english swear words in artwork titles.
swearFilter: true

#If true, action bar messages (messages displayed above a player's toolbar) are disabled.
disableActionBar: false

#If you want to set custom recipes, set this to 'true' then use "/artmap reload" to generate a recipe file.
customRecipes: false

#If true, players with 'artmap.artkit' permission will automatically get a kit of art supplies when they mount an easel. Their normal inventory will be returned to them on dismount.
forceArtKit: false

#If true, return messages to players will not have the [ArtMap] prefix.
hidePrefix: false
